version: "3.8"

services:
  execution:
    image: ethpandaops/ethereumjs:master
    command:
      - --gethGenesis=/el-cl-genesis-data/custom_config_data/genesis.json
      - --dataDir=/execution-data
      - --port=30303
      - --rpc
      - --rpcAddr=0.0.0.0
      - --rpcPort=8545
      - --rpcCors=*
      - --rpcEngine
      - --rpcEngineAddr=0.0.0.0
      - --rpcEnginePort=8551
      - --ws
      - --wsAddr=0.0.0.0
      - --wsPort=8546
      - --wsEnginePort=8547
      - --wsEngineAddr=0.0.0.0
      - --jwt-secret=/el-cl-genesis-data/jwt/jwtsecret
      - --extIP=${IP_ADDRESS}
      - --sync=full
      - --isSingleNode=true
      - --logLevel=info
      - --bootnodes=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10645:8545" 
      - "10646:8546" 
      - "10651:8551" 
      - "11101:9001" 
      - "50403:50403"
    restart: unless-stopped

  beacon:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=11100
      - --enr-tcp-port=11100
      - --listen-address=0.0.0.0
      - --port=11100
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --boot-nodes=enr:-MS4QKjvQWjHjNSlrgJBnwI7j88ULp36kH6FegWreBuiHL0_UGs4EvAxALKLgvKjTFpk6x0zTPyxoXXt0PDeZxlAihgBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjvkwgQAAAOP__________gmlkgnY0gmlwhFhjXm2EcXVpY4Iq-YlzZWNwMjU2azGhAoNhfDA57peBhfKlgRRDYKmjwOUPSPqj97hpWmwycgJdiHN5bmNuZXRzAIN0Y3CCKviDdWRwgir4
      - --checkpoint-sync-url=http://88.99.94.109:9781
      - --disable-optimistic-finalized-sync
      - --disable-backfill-rate-limiting
      - --genesis-backfill
      - --reconstruct-historic-states
      - --reset-payload-statuses
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11100:11100/udp"
      - "11100:11100/tcp" 
      - "4300:4000"
      - "7154:5054"
    depends_on:
      - execution
    restart: unless-stopped

  # validator:
  #   image: sigp/lighthouse:v4.5.0
  #   command:
  #     - lighthouse
  #     - validator_client
  #     - --debug-level=info
  #     - --testnet-dir=/el-cl-genesis-data/custom_config_data
  #     - --validators-dir=/validator-keys/node-1-keystores/keys
  #     - --secrets-dir=/validator-keys/node-1-keystores/secrets
  #     - --init-slashing-protection
  #     - --http
  #     - --unencrypted-http-transport
  #     - --http-address=0.0.0.0
  #     - --http-port=5042
  #     - --beacon-nodes=http://beacon:4000
  #     - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
  #     - --metrics
  #     - --metrics-address=0.0.0.0
  #     - --metrics-allow-origin=*
  #     - --metrics-port=5064
  #   volumes:
  #     - ./el-cl-genesis-data:/el-cl-genesis-data
  #     - ./validator-keys:/validator-keys
  #   ports:
  #     - "7142:5042"
  #     - "7164:5064"
  #   depends_on:
  #     - beacon
  #   restart: unless-stopped
